version: "3.8"

services:
  python-api:
    build: 
      context: .
      dockerfile: Dockerfile.python
    container_name: python-api
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - qdrant
      - ollama
    volumes:
      # Map a local folder to the container's huggingface cache directory
      - ./hf_cache:/root/.cache/huggingface
    environment:
      # Explicitly set the cache directory
      - HF_HOME=/root/.cache/huggingface
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - HF_TOKEN=${HF_TOKEN}

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - WEBHOOK_URL=https://closefisted-discontinuously-leisa.ngrok-free.dev
    depends_on:
      - python-api
    networks:
      - backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      -  C:/Users/Lenovo/.ollama:/root/.ollama
    networks:
      - backend
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_KEEP_ALIVE=-1 # Keeps models in VRAM indefinitely
    command: ["serve"]

volumes:
  n8n_data:
  qdrant_data:
  ollama_data:

networks:
  backend:
    driver: bridge